name: Update V2Ray Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *' # اجرا هر ۶ ساعت
  workflow_dispatch: # امکان اجرای دستی

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # مرحله جدید: دانلود و آماده‌سازی ابزارها
      - name: Download and Setup Tools
        run: |
          # دانلود آخرین نسخه رسمی v2ray-core
          echo "Downloading V2Ray-Core..."
          wget https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip -d v2ray_core
          chmod +x v2ray_core/v2ray

          # دانلود دیتابیس GeoIP
          echo "Downloading GeoIP Database..."
          wget https://git.io/GeoLite2-Country.mmdb -O GeoLite2-Country.mmdb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the update script
        run: python src/main.py

      - name: Set current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '✔️ Update Subscriptions | [UTC] ${{ env.date }}'
          # تمام فایل‌های جدید را اضافه می‌کنیم
          add: 'subscriptions/* reports/*'
          author_name: GitHub Actions
          author_email: actions@github.com
