name: Update V2Ray Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *' # اجرا هر ۶ ساعت
  workflow_dispatch: # امکان اجرای دستی

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # مرحله جدید و نهایی: دانلود و آماده‌سازی هسته رسمی sing-box
      - name: Download and Setup sing-box
        run: |
          # دانلود آخرین نسخه رسمی sing-box
          wget https://github.com/SagerNet/sing-box/releases/download/v1.9.1/sing-box-1.9.1-linux-amd64.tar.gz
          # استخراج فایل
          tar -xvf sing-box-1.9.1-linux-amd64.tar.gz
          # رفتن به پوشه استخراج شده
          cd sing-box-1.9.1-linux-amd64
          # دادن دسترسی اجرایی
          chmod +x sing-box
          # کپی کردن فایل اجرایی به ریشه برای دسترسی آسان‌تر
          cp sing-box ../

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the update script
        run: python src/main.py

      - name: Set current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '✔️ Update Subscriptions | [UTC] ${{ env.date }}'
          add: 'subscriptions/*'
          author_name: GitHub Actions
          author_email: actions@github.com
