# نام گردش کار که در بخش Actions گیت‌هاب نمایش داده می‌شود
name: Update V2Ray Subscriptions

# تعریف رویدادهایی که این گردش کار را فعال می‌کنند
on:
  # اجرای زمان‌بندی شده (مثلاً هر 6 ساعت)
  schedule:
    - cron: '0 */6 * * *' # این عبارت یعنی در دقایق 0 هر 6 ساعت (00:00, 06:00, 12:00, 18:00 UTC)
  
  # امکان اجرای دستی از طریق تب Actions در گیت‌هاب
  workflow_dispatch:

jobs:
  # تعریف یک کار (job) به نام update-configs
  update-configs:
    # استفاده از آخرین نسخه اوبونتو برای اجرای کار
    runs-on: ubuntu-latest

    # اضافه کردن این بخش برای دادن دسترسی نوشتن به اکشن
    permissions:
      contents: write

    steps:
      # مرحله ۱: دریافت کدها از مخزن
      # از اکشن actions/checkout برای دانلود کدهای شما استفاده می‌کند
      - name: Checkout repository
        uses: actions/checkout@v4

      # مرحله ۲: نصب و راه‌اندازی پایتون
      # نسخه‌ی پایتون را مشخص می‌کند
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # می‌توانید از نسخه‌های دیگر هم استفاده کنید

      # مرحله ۳: نصب کتابخانه‌های مورد نیاز
      # دستور pip install را برای نصب نیازمندی‌ها از فایل requirements.txt اجرا می‌کند
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # مرحله ۴: اجرای اسکریپت اصلی پایتون
      # اسکریپت شما را برای انجام فرآیند اصلی اجرا می‌کند
      - name: Run the update script
        run: python src/main.py

      # مرحله ۵: کامیت و پوش کردن تغییرات
      # این اکشن فایل‌های جدید یا تغییریافته در پوشه subscriptions را به مخزن شما اضافه می‌کند
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          # پیامی که برای کامیت ثبت می‌شود. شامل تاریخ و زمان فعلی است
          message: '✔️ Update Subscriptions | [UTC] ${{ env.GIT_DATE }}'
          # پوشه‌ای که باید تغییرات آن بررسی شود
          add: 'subscriptions/*'
          # نام و ایمیل نویسنده کامیت
          author_name: GitHub Actions
          author_email: actions@github.com
        env:
          # تنظیم متغیر محیطی برای تاریخ
          GIT_DATE: $(date -u +'%Y-%m-%d %H:%M:%S')
