name: Update V2Ray Subscriptions

on:
  schedule:
    - cron: '0 */4 * * *' # هر 4 ساعت یک بار
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # دانلود و آماده‌سازی V2Ray Core
      - name: Download and Setup V2Ray
        run: |
          echo "Downloading V2Ray-Core..."
          wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip -q v2ray-linux-64.zip -d v2ray_core
          chmod +x v2ray_core/v2ray
          echo "V2Ray is ready."

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the update script
        run: python src/main.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'subscriptions/*'
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "✅ Update Subscriptions | [UTC] $(date -u +'%Y-%m-%d %H:%M:%S')"
