name: Update V2Ray Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # مرحله جدید: دانلود و آماده‌سازی ابزار تست تخصصی
      - name: Download and Setup V2Ray-Ping
        run: |
          # دانلود آخرین نسخه ابزار از گیت‌هاب
          wget https://github.com/hossinasaadi/v2ray-ping/releases/latest/download/v2ray-ping_linux_amd64.zip
          # از حالت فشرده خارج کردن
          unzip v2ray-ping_linux_amd64.zip
          # دادن دسترسی اجرایی به فایل
          chmod +x v2ray-ping

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the update script
        # اجرای اسکریپت پایتون که حالا از ابزار تست استفاده می‌کند
        run: python src/main.py

      - name: Set current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '✔️ Update Subscriptions | [UTC] ${{ env.date }}'
          add: 'subscriptions/*'
          author_name: GitHub Actions
          author_email: actions@github.com
