name: Update V2Ray Subscriptions

on:
  schedule:
    - cron: '0 */4 * * *' # هر 4 ساعت
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download and Setup Tools
        run: |
          echo "Downloading GeoIP Database..."
          wget -q https://git.io/GeoLite2-Country.mmdb -O GeoLite2-Country.mmdb
          echo "GeoIP DB is ready."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the main script to test and categorize configs
        run: python src/main.py

      # مرحله جدید: ساخت README.md نهایی
      - name: Generate README.md from template
        run: python src/generate_readme.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # اضافه کردن تمام فایل‌های جدید
          git add subscriptions/ reports/ README.md
          if ! git diff --staged --quiet; then
            git commit -m "✅ Update Subscriptions & Stats | [UTC] $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
