name: Update Config Sources

on:
  schedule:
    - cron: '0 */4 * * *' # هر 4 ساعت
  workflow_dispatch:

jobs:
  update-sources:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      # از همان اسکریپت قبلی برای جمع‌آوری استفاده می‌کنیم
      - name: Run Collection Script
        run: python src/main.py 

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # فقط فایل‌های داخل پوشه subscriptions را اضافه کن
          git add subscriptions/
          if ! git diff --staged --quiet; then
            git commit -m "✅ Update Config Sources | [UTC] $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
