name: Update V2Ray Subscriptions

on:
  schedule:
    - cron: '0 */4 * * *' # هر 4 ساعت
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download and Setup Tools
        run: |
          echo "Downloading V2Ray-Core..."
          wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip -q v2ray-linux-64.zip -d v2ray_core
          chmod +x v2ray_core/v2ray
          echo "V2Ray is ready."

          echo "Downloading GeoIP Database..."
          wget -q https://git.io/GeoLite2-Country.mmdb -O GeoLite2-Country.mmdb
          echo "GeoIP DB is ready."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the update script
        run: python src/main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # اضافه کردن تمام فایل‌های جدید در پوشه subscriptions
          git add subscriptions/
          # فقط در صورتی کامیت کن که تغییری وجود داشته باشد
          if ! git diff --staged --quiet; then
            git commit -m "✅ Update Subscriptions | [UTC] $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
